import { FIXTURE_NOW, fixtureUser, money } from './fixtures'
import type {
  InvestmentActivity,
  InvestmentHoldingSnapshot,
  InvestmentSecurity,
  MarketSecuritySearchResult,
} from '../src/api/models'

const security: InvestmentSecurity = {
  id: 'security-fixture',
  provider: 'plaid',
  externalSecurityId: 'EXM',
  institutionId: null,
  institutionSecurityId: null,
  name: 'Example international equity fund with a long security name',
  tickerSymbol: 'EXM',
  isin: null,
  cusip: null,
  sedol: null,
  type: 'etf',
  subtype: null,
  isCashEquivalent: false,
  closePrice: '42.1234',
  closePriceAsOf: '2026-09-04',
  updateDatetime: FIXTURE_NOW,
  isoCurrencyCode: 'EUR',
  unofficialCurrencyCode: null,
  marketIdentifierCode: null,
  sector: null,
  industry: null,
  createdAt: FIXTURE_NOW,
  updatedAt: FIXTURE_NOW,
  userId: fixtureUser.id,
}
export const holding: InvestmentHoldingSnapshot = {
  id: 'holding-fixture',
  accountId: 'investment',
  securityId: security.id,
  provider: 'plaid',
  snapshotDate: '2026-09-06',
  quantity: '1234.56789',
  costBasis: '40000',
  institutionPrice: '42.1234',
  institutionPriceAsOf: '2026-09-04',
  institutionPriceDatetime: FIXTURE_NOW,
  institutionValue: '52003.876',
  isoCurrencyCode: 'EUR',
  unofficialCurrencyCode: null,
  accountCurrency: 'USD',
  exchangeRateToAccountCurrency: '1.1',
  accountValue: '57204.2636',
  vestedQuantity: null,
  vestedValue: null,
  security,
  createdAt: FIXTURE_NOW,
  updatedAt: FIXTURE_NOW,
  userId: fixtureUser.id,
}
export const activity: InvestmentActivity = {
  id: 'activity-fixture',
  activityId: 'activity-fixture',
  accountId: 'investment',
  accountName: 'Investment portfolio',
  provider: 'plaid',
  externalActivityId: null,
  activityDate: '2026-09-04',
  providerDate: '2026-09-04',
  providerDatetime: null,
  amount: money('421234', 'negative', 'EUR'),
  security,
  externalSecurityId: null,
  name: 'Buy EXM',
  providerDescription: 'Example purchase',
  quantity: '100',
  price: '42.1234',
  fees: '0.25',
  investmentType: 'buy',
  investmentSubtype: 'buy',
  cancelExternalActivityId: null,
}
export const securities: Array<MarketSecuritySearchResult> = [
  {
    symbol: 'EXM',
    name: security.name!,
    quoteType: 'ETF',
    exchangeCode: 'TEST',
    exchangeName: 'Example exchange',
    currency: 'EUR',
    marketIdentifierCode: null,
  },
  {
    symbol: 'ZERO',
    name: 'Example zero balance security',
    quoteType: 'EQUITY',
    exchangeCode: 'TEST',
    exchangeName: 'Example exchange',
    currency: 'USD',
    marketIdentifierCode: null,
  },
]
