/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AccountSummaryType } from './accountSummaryType';
import type { MoneyWithSign } from './moneyWithSign';
import type { AccountSummaryConvertedCurrentBalance } from './accountSummaryConvertedCurrentBalance';
import type { AccountSummaryConvertedEffectiveBalance } from './accountSummaryConvertedEffectiveBalance';

export interface AccountSummary {
  id: string;
  /** @nullable */
  name: string | null;
  type: AccountSummaryType;
  /** @nullable */
  subType: string | null;
  currentBalance: MoneyWithSign;
  convertedCurrentBalance: AccountSummaryConvertedCurrentBalance;
  effectiveBalance: MoneyWithSign;
  convertedEffectiveBalance: AccountSummaryConvertedEffectiveBalance;
  /** @nullable */
  changePercent: number | null;
  /** @nullable */
  institutionName: string | null;
}
