/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AccountType } from './accountType';
import type { AccountSubType } from './accountSubType';
import type { AccountBankLink } from './accountBankLink';
import type { MoneyWithSign } from './moneyWithSign';

export interface Account {
  id: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  mask?: string | null;
  type: typeof AccountType[keyof typeof AccountType] ;
  /** @nullable */
  subType: AccountSubType;
  /** @nullable */
  externalAccountId?: string | null;
  /** @nullable */
  bankLinkId?: string | null;
  bankLink?: AccountBankLink;
  availableBalance: MoneyWithSign;
  currentBalance: MoneyWithSign;
  createdAt: string;
  updatedAt: string;
  userId: string;
}
