/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AccountSummaryType = typeof AccountSummaryType[keyof typeof AccountSummaryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountSummaryType = {
  investment: 'investment',
  credit: 'credit',
  depository: 'depository',
  loan: 'loan',
  brokerage: 'brokerage',
  other: 'other',
} as const;
