/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign';
import type { AccountType } from './accountType';
import type { AccountSubType } from './accountSubType';
import type { AccountBankLinkStatus } from './accountBankLinkStatus';

export interface Account {
  id: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  mask?: string | null;
  availableBalance: MoneyWithSign;
  currentBalance: MoneyWithSign;
  type: AccountType;
  /** @nullable */
  subType: AccountSubType;
  /** @nullable */
  externalAccountId?: string | null;
  /** @nullable */
  bankLinkId?: string | null;
  /** @nullable */
  institutionName?: string | null;
  /** @nullable */
  bankLinkStatus?: AccountBankLinkStatus;
  /** @nullable */
  providerName?: string | null;
  /** @nullable */
  lastSyncedAt?: string | null;
  createdAt: string;
  updatedAt: string;
  userId: string;
}
