/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign';
import type { AccountSummaryConvertedCurrentBalanceAllOf } from './accountSummaryConvertedCurrentBalanceAllOf';

export type AccountSummaryConvertedCurrentBalance = MoneyWithSign & AccountSummaryConvertedCurrentBalanceAllOf;
