/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { Account } from './account'
import type { BalanceWithConvertedBalance } from './balanceWithConvertedBalance'

export interface AccountBalanceResult {
  account: Account
  availableBalance: BalanceWithConvertedBalance
  currentBalance: BalanceWithConvertedBalance
  effectiveBalance: BalanceWithConvertedBalance
}
