/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AccountSummaryType } from './accountSummaryType'
import type { MoneyWithSign } from './moneyWithSign'

export interface AccountSummary {
  id: string
  /** @nullable */
  name: string | null
  type: AccountSummaryType
  /** @nullable */
  subType: string | null
  currentBalance: MoneyWithSign
  /** @nullable */
  changePercent: number | null
}
