/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AccountBalanceResultProvenanceCoverage } from './accountBalanceResultProvenanceCoverage'

export type AccountBalanceResultProvenance = {
  requestedDate: string
  /** @nullable */
  snapshotId: string | null
  /** @nullable */
  snapshotDate: string | null
  /** @nullable */
  snapshotType: string | null
  /** @nullable */
  snapshotUpdatedAt: string | null
  carriedForward: boolean
  coverage: AccountBalanceResultProvenanceCoverage
}
