/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign';
import type { AccountWithConvertedBalanceAllOfConvertedAvailableBalanceAllOf } from './accountWithConvertedBalanceAllOfConvertedAvailableBalanceAllOf';

export type AccountWithConvertedBalanceAllOfConvertedAvailableBalance = MoneyWithSign & AccountWithConvertedBalanceAllOfConvertedAvailableBalanceAllOf;
