/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AccountBalanceResultProvenanceCoverage =
  (typeof AccountBalanceResultProvenanceCoverage)[keyof typeof AccountBalanceResultProvenanceCoverage]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountBalanceResultProvenanceCoverage = {
  recorded: 'recorded',
  carried_forward: 'carried_forward',
  missing: 'missing',
} as const
