/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AccountValuationMode =
  (typeof AccountValuationMode)[keyof typeof AccountValuationMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountValuationMode = {
  balance: 'balance',
  holdings: 'holdings',
} as const
