/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type AccountBankLinkStatus = typeof AccountBankLinkStatus[keyof typeof AccountBankLinkStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountBankLinkStatus = {
  OK: 'OK',
  ERROR: 'ERROR',
  PENDING_REAUTH: 'PENDING_REAUTH',
} as const;
