/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AnalysisRuleType =
  (typeof AnalysisRuleType)[keyof typeof AnalysisRuleType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisRuleType = {
  exclude: 'exclude',
  neutralize: 'neutralize',
} as const
