/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AnalysisRuleViewExcludeScopeAllOfOneOfThreeMode =
  (typeof AnalysisRuleViewExcludeScopeAllOfOneOfThreeMode)[keyof typeof AnalysisRuleViewExcludeScopeAllOfOneOfThreeMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisRuleViewExcludeScopeAllOfOneOfThreeMode = {
  selected: 'selected',
} as const
