/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AnalysisRuleViewInflowScopeAllOfOneOfThreeMode =
  (typeof AnalysisRuleViewInflowScopeAllOfOneOfThreeMode)[keyof typeof AnalysisRuleViewInflowScopeAllOfOneOfThreeMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisRuleViewInflowScopeAllOfOneOfThreeMode = {
  selected: 'selected',
} as const
