/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisAuditTransactionAmountSign } from './analysisAuditTransactionAmountSign'

export type AnalysisAuditTransactionAmount = {
  /** @pattern ^(0|[1-9]\d{0,77})$ */
  amount: string
  currency: string
  sign: AnalysisAuditTransactionAmountSign
}
