/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AnalysisRuleViewInflowScopeAllOfOneOfMode =
  (typeof AnalysisRuleViewInflowScopeAllOfOneOfMode)[keyof typeof AnalysisRuleViewInflowScopeAllOfOneOfMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisRuleViewInflowScopeAllOfOneOfMode = {
  all: 'all',
} as const
