/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisCategoryScopeOneOfThreeMode } from './analysisCategoryScopeOneOfThreeMode'

export type AnalysisCategoryScopeOneOfThree = {
  mode: AnalysisCategoryScopeOneOfThreeMode
  categoryIds?: string[]
  includeUncategorized?: boolean
}
