/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisRuleViewExcludeScopeAllOfOneOf } from './analysisRuleViewExcludeScopeAllOfOneOf'
import type { AnalysisRuleViewExcludeScopeAllOfOneOfThree } from './analysisRuleViewExcludeScopeAllOfOneOfThree'
import type { AnalysisRuleViewExcludeScopeAllOfOneOfFive } from './analysisRuleViewExcludeScopeAllOfOneOfFive'

export type AnalysisRuleViewExcludeScopeAllOf =
  | AnalysisRuleViewExcludeScopeAllOfOneOf
  | AnalysisRuleViewExcludeScopeAllOfOneOfThree
  | AnalysisRuleViewExcludeScopeAllOfOneOfFive
