/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisAuditExcludedRowType } from './analysisAuditExcludedRowType'
import type { AnalysisAuditTransaction } from './analysisAuditTransaction'

export interface AnalysisAuditExcludedRow {
  id: string
  type: AnalysisAuditExcludedRowType
  groupKey: string
  groupLabel: string
  ruleId: string
  ruleName: string
  transaction: AnalysisAuditTransaction
}
