/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AnalysisRuleViewOutflowScopeAllOfOneOfMode =
  (typeof AnalysisRuleViewOutflowScopeAllOfOneOfMode)[keyof typeof AnalysisRuleViewOutflowScopeAllOfOneOfMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisRuleViewOutflowScopeAllOfOneOfMode = {
  all: 'all',
} as const
