/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisCategoryScopeView } from './analysisCategoryScopeView'
import type { AnalysisRuleViewInflowScopeAllOf } from './analysisRuleViewInflowScopeAllOf'

export type AnalysisRuleViewInflowScope = AnalysisCategoryScopeView &
  AnalysisRuleViewInflowScopeAllOf
