/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AnalysisAuditTransactionAmountSign =
  (typeof AnalysisAuditTransactionAmountSign)[keyof typeof AnalysisAuditTransactionAmountSign]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisAuditTransactionAmountSign = {
  positive: 'positive',
  negative: 'negative',
} as const
