/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AnalysisCategoryScopeOneOfMode =
  (typeof AnalysisCategoryScopeOneOfMode)[keyof typeof AnalysisCategoryScopeOneOfMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisCategoryScopeOneOfMode = {
  all: 'all',
} as const
