/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisAuditNeutralizedRowType } from './analysisAuditNeutralizedRowType'
import type { AnalysisAuditTransaction } from './analysisAuditTransaction'

export interface AnalysisAuditNeutralizedRow {
  id: string
  type: AnalysisAuditNeutralizedRowType
  groupKey: string
  groupLabel: string
  ruleId: string
  ruleName: string
  outflow: AnalysisAuditTransaction
  inflow: AnalysisAuditTransaction
}
