/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisRuleViewOutflowScopeAllOfOneOf } from './analysisRuleViewOutflowScopeAllOfOneOf'
import type { AnalysisRuleViewOutflowScopeAllOfOneOfThree } from './analysisRuleViewOutflowScopeAllOfOneOfThree'
import type { AnalysisRuleViewOutflowScopeAllOfOneOfFive } from './analysisRuleViewOutflowScopeAllOfOneOfFive'

export type AnalysisRuleViewOutflowScopeAllOf =
  | AnalysisRuleViewOutflowScopeAllOfOneOf
  | AnalysisRuleViewOutflowScopeAllOfOneOfThree
  | AnalysisRuleViewOutflowScopeAllOfOneOfFive
