/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisRuleViewOutflowScopeAllOfOneOfThreeMode } from './analysisRuleViewOutflowScopeAllOfOneOfThreeMode'
import type { AnalysisRuleCategoryView } from './analysisRuleCategoryView'

export type AnalysisRuleViewOutflowScopeAllOfOneOfThree = {
  mode: AnalysisRuleViewOutflowScopeAllOfOneOfThreeMode
  includeUncategorized: boolean
  categories: AnalysisRuleCategoryView[]
}
