/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisRuleType } from './analysisRuleType'

export interface AnalysisRuleConflict {
  ruleId: string
  name: string
  type: AnalysisRuleType
  label: string
  /** @nullable */
  archivedAt?: string | null
}
