/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AnalysisRuleViewExcludeScopeAllOfOneOfMode =
  (typeof AnalysisRuleViewExcludeScopeAllOfOneOfMode)[keyof typeof AnalysisRuleViewExcludeScopeAllOfOneOfMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalysisRuleViewExcludeScopeAllOfOneOfMode = {
  all: 'all',
} as const
