/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisRuleViewInflowScopeAllOfOneOf } from './analysisRuleViewInflowScopeAllOfOneOf'
import type { AnalysisRuleViewInflowScopeAllOfOneOfThree } from './analysisRuleViewInflowScopeAllOfOneOfThree'
import type { AnalysisRuleViewInflowScopeAllOfOneOfFive } from './analysisRuleViewInflowScopeAllOfOneOfFive'

export type AnalysisRuleViewInflowScopeAllOf =
  | AnalysisRuleViewInflowScopeAllOfOneOf
  | AnalysisRuleViewInflowScopeAllOfOneOfThree
  | AnalysisRuleViewInflowScopeAllOfOneOfFive
