/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisCategoryScopeViewOneOf } from './analysisCategoryScopeViewOneOf'
import type { AnalysisCategoryScopeViewOneOfThree } from './analysisCategoryScopeViewOneOfThree'

export type AnalysisCategoryScopeView =
  | AnalysisCategoryScopeViewOneOf
  | AnalysisCategoryScopeViewOneOfThree
