/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AppearancePreferenceAccents = {
  /**
   * @nullable
   * @pattern ^#[0-9a-fA-F]{6}$
   */
  light?: string | null
  /**
   * @nullable
   * @pattern ^#[0-9a-fA-F]{6}$
   */
  dark?: string | null
  /**
   * @nullable
   * @pattern ^#[0-9a-fA-F]{6}$
   */
  oled?: string | null
}
