/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AppearancePreferenceMode } from './appearancePreferenceMode'

export interface AppearancePreference {
  mode: AppearancePreferenceMode
  monospaceAmounts?: boolean
  /**
   * @nullable
   * @pattern ^#[0-9a-fA-F]{6}$
   */
  accent: string | null
}
