/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type AppearancePreferenceMode =
  (typeof AppearancePreferenceMode)[keyof typeof AppearancePreferenceMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppearancePreferenceMode = {
  light: 'light',
  dark: 'dark',
  oled: 'oled',
} as const
