/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign';

export type BalanceSnapshotWithConvertedBalanceAllOfConvertedCurrentBalance = MoneyWithSign | null;
