/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { BalanceSnapshotSnapshotType } from './balanceSnapshotSnapshotType'
import type { MoneyWithSign } from './moneyWithSign'

export interface BalanceSnapshot {
  id: string
  accountId: string
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  snapshotDate: string
  snapshotType: BalanceSnapshotSnapshotType
  availableBalance: MoneyWithSign
  currentBalance: MoneyWithSign
  createdAt: string
  updatedAt: string
  userId: string
}
