/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface BalancesRequest {
  accountIds: string[];
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  startDate: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  endDate: string;
}
