/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type BalanceAdjustmentFlowDirection =
  (typeof BalanceAdjustmentFlowDirection)[keyof typeof BalanceAdjustmentFlowDirection]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BalanceAdjustmentFlowDirection = {
  inflow: 'inflow',
  outflow: 'outflow',
} as const
