/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type BalanceQueryControllerGetBalancesParams = {
/**
 * End date (YYYY-MM-DD, inclusive)
 */
endDate: unknown;
/**
 * Start date (YYYY-MM-DD, inclusive)
 */
startDate: unknown;
/**
 * Comma-separated list of account UUIDs
 */
accountIds: unknown;
};
