/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { BalanceQueryControllerGetDashboardSummaryPeriod } from './balanceQueryControllerGetDashboardSummaryPeriod'

export type BalanceQueryControllerGetDashboardSummaryParams = {
  /**
   * Valid calendar date (YYYY-MM-DD, inclusive)
   */
  endDate: string
  period: BalanceQueryControllerGetDashboardSummaryPeriod
}
