/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign';
import type { RateWithSource } from './rateWithSource';

export interface BalanceWithConvertedBalance {
  balance: MoneyWithSign;
  convertedBalance?: MoneyWithSign;
  exchangeRate?: RateWithSource;
}
