/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { BalanceSnapshotWithConvertedBalanceAllOfConvertedCurrentBalance } from './balanceSnapshotWithConvertedBalanceAllOfConvertedCurrentBalance';
import type { BalanceSnapshotWithConvertedBalanceAllOfConvertedAvailableBalance } from './balanceSnapshotWithConvertedBalanceAllOfConvertedAvailableBalance';
import type { MoneyWithSign } from './moneyWithSign';
import type { BalanceSnapshotWithConvertedBalanceAllOfConvertedEffectiveBalance } from './balanceSnapshotWithConvertedBalanceAllOfConvertedEffectiveBalance';

export type BalanceSnapshotWithConvertedBalanceAllOf = {
  convertedCurrentBalance: BalanceSnapshotWithConvertedBalanceAllOfConvertedCurrentBalance;
  convertedAvailableBalance: BalanceSnapshotWithConvertedBalanceAllOfConvertedAvailableBalance;
  effectiveBalance: MoneyWithSign;
  convertedEffectiveBalance: BalanceSnapshotWithConvertedBalanceAllOfConvertedEffectiveBalance;
};
