/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type BulkTransactionCategoryReviewFiltersAmountSign =
  (typeof BulkTransactionCategoryReviewFiltersAmountSign)[keyof typeof BulkTransactionCategoryReviewFiltersAmountSign]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkTransactionCategoryReviewFiltersAmountSign = {
  positive: 'positive',
  negative: 'negative',
} as const
