/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { BulkCustomCategoryActionDtoOneOf } from './bulkCustomCategoryActionDtoOneOf'
import type { BulkCustomCategoryActionDtoOneOfThree } from './bulkCustomCategoryActionDtoOneOfThree'
import type { BulkCustomCategoryActionDtoOneOfFive } from './bulkCustomCategoryActionDtoOneOfFive'

export type BulkCustomCategoryActionDto =
  | BulkCustomCategoryActionDtoOneOf
  | BulkCustomCategoryActionDtoOneOfThree
  | BulkCustomCategoryActionDtoOneOfFive
