/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { BulkCustomCategoryActionDtoOneOfAction } from './bulkCustomCategoryActionDtoOneOfAction'

export type BulkCustomCategoryActionDtoOneOf = {
  /**
   * @minItems 1
   * @maxItems 500
   */
  categoryIds: string[]
  action: BulkCustomCategoryActionDtoOneOfAction
}
