/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type BulkCustomCategoryActionDtoOneOfFiveAction =
  (typeof BulkCustomCategoryActionDtoOneOfFiveAction)[keyof typeof BulkCustomCategoryActionDtoOneOfFiveAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkCustomCategoryActionDtoOneOfFiveAction = {
  setPrimary: 'setPrimary',
} as const
