/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { BulkTransactionCategoryReviewFiltersAmountSign } from './bulkTransactionCategoryReviewFiltersAmountSign'
import type { TransactionCategoryReviewStatus } from './transactionCategoryReviewStatus'

export interface BulkTransactionCategoryReviewFilters {
  accountId?: string
  startDate?: string
  endDate?: string
  categoryPrimary?: string
  amountSign?: BulkTransactionCategoryReviewFiltersAmountSign
  categoryReviewStatus?: TransactionCategoryReviewStatus
}
