/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { BulkCustomCategoryActionDtoOneOfSevenAction } from './bulkCustomCategoryActionDtoOneOfSevenAction'

export type BulkCustomCategoryActionDtoOneOfSeven = {
  /**
   * @minItems 1
   * @maxItems 500
   */
  categoryIds: string[]
  action: BulkCustomCategoryActionDtoOneOfSevenAction
  /**
   * @minLength 1
   * @maxLength 80
   */
  primary: string
}
