/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type BulkCustomCategoryActionDtoOneOfAction =
  (typeof BulkCustomCategoryActionDtoOneOfAction)[keyof typeof BulkCustomCategoryActionDtoOneOfAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkCustomCategoryActionDtoOneOfAction = {
  archive: 'archive',
} as const
