/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { BulkCustomCategoryActionDtoOneOfThreeAction } from './bulkCustomCategoryActionDtoOneOfThreeAction'

export type BulkCustomCategoryActionDtoOneOfThree = {
  /**
   * @minItems 1
   * @maxItems 500
   */
  categoryIds: string[]
  action: BulkCustomCategoryActionDtoOneOfThreeAction
}
