/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type BulkCategoryActionResponseSkippedItemReason =
  (typeof BulkCategoryActionResponseSkippedItemReason)[keyof typeof BulkCategoryActionResponseSkippedItemReason]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkCategoryActionResponseSkippedItemReason = {
  not_found: 'not_found',
  not_owned: 'not_owned',
  archived: 'archived',
  duplicate_conflict: 'duplicate_conflict',
} as const
