/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface Category {
  id: string
  primary: string
  detailed: string
  description: string
  /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
  color: string
  /** @nullable */
  archivedAt?: string | null
  createdAt: string
  updatedAt: string
}
