/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleConditionAnyOfOnetwoField } from './categorizationRuleConditionAnyOfOnetwoField'
import type { CategorizationRuleConditionAnyOfOnetwoOperator } from './categorizationRuleConditionAnyOfOnetwoOperator'
import type { CategorizationRuleConditionAnyOfOnetwoValue } from './categorizationRuleConditionAnyOfOnetwoValue'

export type CategorizationRuleConditionAnyOfOnetwo = {
  field: CategorizationRuleConditionAnyOfOnetwoField
  operator: CategorizationRuleConditionAnyOfOnetwoOperator
  value: CategorizationRuleConditionAnyOfOnetwoValue
}
