/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface CategorizationRuleChangeImpact {
  matchedBefore: number
  matchedAfter: number
  newlyMatched: number
  noLongerMatched: number
  winningBefore: number
  winningAfter: number
  winnerChanged: number
  skippedManual: number
  historicalAssignments: number
  historicalAssignmentsUntouched: boolean
}
