/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleConditionAnyOfFourOperator =
  (typeof CategorizationRuleConditionAnyOfFourOperator)[keyof typeof CategorizationRuleConditionAnyOfFourOperator]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleConditionAnyOfFourOperator = {
  equals: 'equals',
  in: 'in',
} as const
