/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleChangePreviewAction } from './categorizationRuleChangePreviewAction'
import type { CategorizationRuleView } from './categorizationRuleView'
import type { CategorizationRuleChangeImpact } from './categorizationRuleChangeImpact'
import type { Transaction } from './transaction'

export interface CategorizationRuleChangePreview {
  action: CategorizationRuleChangePreviewAction
  currentRule: CategorizationRuleView
  proposedRule: CategorizationRuleView
  impact: CategorizationRuleChangeImpact
  transactions: Transaction[]
}
