/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleConditionAnyOfField } from './categorizationRuleConditionAnyOfField'
import type { CategorizationRuleConditionAnyOfOperator } from './categorizationRuleConditionAnyOfOperator'

export type CategorizationRuleConditionAnyOf = {
  field: CategorizationRuleConditionAnyOfField
  operator: CategorizationRuleConditionAnyOfOperator
  /** @minLength 1 */
  value: string
}
