/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleConditionAnyOfOperator =
  (typeof CategorizationRuleConditionAnyOfOperator)[keyof typeof CategorizationRuleConditionAnyOfOperator]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleConditionAnyOfOperator = {
  equals: 'equals',
  contains: 'contains',
  startsWith: 'startsWith',
  endsWith: 'endsWith',
} as const
