/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleSuggestionGenerationStatus =
  (typeof CategorizationRuleSuggestionGenerationStatus)[keyof typeof CategorizationRuleSuggestionGenerationStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleSuggestionGenerationStatus = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const
