/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleChangePreviewAction =
  (typeof CategorizationRuleChangePreviewAction)[keyof typeof CategorizationRuleChangePreviewAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleChangePreviewAction = {
  edit: 'edit',
  archive: 'archive',
  restore: 'restore',
} as const
