/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleSuggestionGeneratedBy =
  (typeof CategorizationRuleSuggestionGeneratedBy)[keyof typeof CategorizationRuleSuggestionGeneratedBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleSuggestionGeneratedBy = {
  mastra: 'mastra',
} as const
