/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleConditionAnyOfEightValue =
  (typeof CategorizationRuleConditionAnyOfEightValue)[keyof typeof CategorizationRuleConditionAnyOfEightValue]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleConditionAnyOfEightValue = {
  positive: 'positive',
  negative: 'negative',
} as const
