/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleCategoryView } from './categorizationRuleCategoryView'
import type { CategorizationRuleCondition } from './categorizationRuleCondition'

export interface CategorizationRuleView {
  id: string
  name: string
  priority: number
  targetCategoryId: string
  targetCategory: CategorizationRuleCategoryView
  conditions: CategorizationRuleCondition[]
  /** @nullable */
  archivedAt?: string | null
  createdAt: string
  updatedAt: string
}
