/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleConditionAnyOfOnetwoOperator =
  (typeof CategorizationRuleConditionAnyOfOnetwoOperator)[keyof typeof CategorizationRuleConditionAnyOfOnetwoOperator]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleConditionAnyOfOnetwoOperator = {
  equals: 'equals',
  greaterThan: 'greaterThan',
  lessThan: 'lessThan',
  between: 'between',
} as const
