/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleSuggestionStatus =
  (typeof CategorizationRuleSuggestionStatus)[keyof typeof CategorizationRuleSuggestionStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleSuggestionStatus = {
  pending: 'pending',
  accepted: 'accepted',
  dismissed: 'dismissed',
  superseded: 'superseded',
} as const
