/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleSuggestionGenerationStatus } from './categorizationRuleSuggestionGenerationStatus'

export interface CategorizationRuleSuggestionGeneration {
  id: string
  userId: string
  status: CategorizationRuleSuggestionGenerationStatus
  model: string
  ignoredCategoryIds: string[]
  /** @nullable */
  startedAt: string | null
  /** @nullable */
  completedAt: string | null
  /** @nullable */
  failedAt: string | null
  /** @nullable */
  errorMessage: string | null
  createdAt: string
  updatedAt: string
}
