/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleCategoryView } from './categorizationRuleCategoryView'
import type { CategorizationRuleCondition } from './categorizationRuleCondition'
import type { CategorizationRuleSuggestionStatus } from './categorizationRuleSuggestionStatus'
import type { Transaction } from './transaction'
import type { CategorizationRuleSuggestionGeneratedBy } from './categorizationRuleSuggestionGeneratedBy'

export interface CategorizationRuleSuggestion {
  id: string
  userId: string
  generationId: string
  name: string
  targetCategoryId: string
  targetCategory: CategorizationRuleCategoryView
  priority: number
  conditions: CategorizationRuleCondition[]
  rationale: string
  status: CategorizationRuleSuggestionStatus
  /** @nullable */
  acceptedRuleId: string | null
  matched: number
  updated: number
  skippedManual: number
  manualAgreement: number
  manualConflicts: number
  existingRuleOverlap: number
  previewTransactions: Transaction[]
  generatedBy: CategorizationRuleSuggestionGeneratedBy
  model: string
  createdAt: string
  updatedAt: string
}
