/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleConditionAnyOfFourField =
  (typeof CategorizationRuleConditionAnyOfFourField)[keyof typeof CategorizationRuleConditionAnyOfFourField]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleConditionAnyOfFourField = {
  accountId: 'accountId',
} as const
