/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorySource =
  (typeof CategorySource)[keyof typeof CategorySource]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorySource = {
  plaid: 'plaid',
  user: 'user',
} as const
