/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategoryConflictSource =
  (typeof CategoryConflictSource)[keyof typeof CategoryConflictSource]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryConflictSource = {
  plaid: 'plaid',
  user: 'user',
} as const
