/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleConditionAnyOfOnetwoValueAnyOf = {
  /**
   * @maxLength 156
   * @pattern ^-?(0|[1-9]\d*)(\.\d+)?$
   */
  min?: string
  /**
   * @maxLength 156
   * @pattern ^-?(0|[1-9]\d*)(\.\d+)?$
   */
  max?: string
}
