/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface CategoryAggregate {
  primaryCategory: string
  /** @pattern ^(0|[1-9]\d{0,77})$ */
  totalAmount: string
  currency: string
  transactionCount: number
  /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
  color: string
}
