/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleConditionAnyOfEightField } from './categorizationRuleConditionAnyOfEightField'
import type { CategorizationRuleConditionAnyOfEightOperator } from './categorizationRuleConditionAnyOfEightOperator'
import type { CategorizationRuleConditionAnyOfEightValue } from './categorizationRuleConditionAnyOfEightValue'

export type CategorizationRuleConditionAnyOfEight = {
  field: CategorizationRuleConditionAnyOfEightField
  operator: CategorizationRuleConditionAnyOfEightOperator
  value: CategorizationRuleConditionAnyOfEightValue
}
