/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleConditionAnyOf } from './categorizationRuleConditionAnyOf'
import type { CategorizationRuleConditionAnyOfFour } from './categorizationRuleConditionAnyOfFour'
import type { CategorizationRuleConditionAnyOfEight } from './categorizationRuleConditionAnyOfEight'
import type { CategorizationRuleConditionAnyOfOnetwo } from './categorizationRuleConditionAnyOfOnetwo'

export type CategorizationRuleCondition =
  | CategorizationRuleConditionAnyOf
  | CategorizationRuleConditionAnyOfFour
  | CategorizationRuleConditionAnyOfEight
  | CategorizationRuleConditionAnyOfOnetwo
