/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleConditionAnyOfFourField } from './categorizationRuleConditionAnyOfFourField'
import type { CategorizationRuleConditionAnyOfFourOperator } from './categorizationRuleConditionAnyOfFourOperator'
import type { CategorizationRuleConditionAnyOfFourValue } from './categorizationRuleConditionAnyOfFourValue'

export type CategorizationRuleConditionAnyOfFour = {
  field: CategorizationRuleConditionAnyOfFourField
  operator: CategorizationRuleConditionAnyOfFourOperator
  value: CategorizationRuleConditionAnyOfFourValue
}
