/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CategorizationRuleConditionAnyOfField =
  (typeof CategorizationRuleConditionAnyOfField)[keyof typeof CategorizationRuleConditionAnyOfField]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategorizationRuleConditionAnyOfField = {
  merchantName: 'merchantName',
  providerTransactionName: 'providerTransactionName',
  originalDescription: 'originalDescription',
  merchantEntityId: 'merchantEntityId',
  website: 'website',
  providerCategoryPrimary: 'providerCategoryPrimary',
  providerCategoryDetailed: 'providerCategoryDetailed',
} as const
