/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CreateAnalysisRuleDtoOneOfThreeType =
  (typeof CreateAnalysisRuleDtoOneOfThreeType)[keyof typeof CreateAnalysisRuleDtoOneOfThreeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAnalysisRuleDtoOneOfThreeType = {
  neutralize: 'neutralize',
} as const
