/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface CreatePersonalAccessTokenDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string
  expiresAt?: string
}
