/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type CreateAccountDtoRawApiAccountSubType = typeof CreateAccountDtoRawApiAccountSubType[keyof typeof CreateAccountDtoRawApiAccountSubType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAccountDtoRawApiAccountSubType = {
  '401a': '401a',
  '401k': '401k',
  '403B': '403B',
  '457b': '457b',
  NUMBER_529: '529',
  auto: 'auto',
  brokerage: 'brokerage',
  business: 'business',
  cash_isa: 'cash isa',
  cash_management: 'cash management',
  cd: 'cd',
  checking: 'checking',
  commercial: 'commercial',
  construction: 'construction',
  consumer: 'consumer',
  credit_card: 'credit card',
  crypto_exchange: 'crypto exchange',
  ebt: 'ebt',
  education_savings_account: 'education savings account',
  fixed_annuity: 'fixed annuity',
  gic: 'gic',
  health_reimbursement_arrangement: 'health reimbursement arrangement',
  home_equity: 'home equity',
  hsa: 'hsa',
  isa: 'isa',
  ira: 'ira',
  keogh: 'keogh',
  lif: 'lif',
  life_insurance: 'life insurance',
  line_of_credit: 'line of credit',
  lira: 'lira',
  loan: 'loan',
  lrif: 'lrif',
  lrsp: 'lrsp',
  money_market: 'money market',
  mortgage: 'mortgage',
  mutual_fund: 'mutual fund',
  'non-custodial_wallet': 'non-custodial wallet',
  'non-taxable_brokerage_account': 'non-taxable brokerage account',
  other: 'other',
  other_insurance: 'other insurance',
  other_annuity: 'other annuity',
  overdraft: 'overdraft',
  paypal: 'paypal',
  payroll: 'payroll',
  pension: 'pension',
  prepaid: 'prepaid',
  prif: 'prif',
  profit_sharing_plan: 'profit sharing plan',
  rdsp: 'rdsp',
  resp: 'resp',
  retirement: 'retirement',
  rlif: 'rlif',
  roth: 'roth',
  roth_401k: 'roth 401k',
  rrif: 'rrif',
  rrsp: 'rrsp',
  sarsep: 'sarsep',
  savings: 'savings',
  sep_ira: 'sep ira',
  simple_ira: 'simple ira',
  sipp: 'sipp',
  stock_plan: 'stock plan',
  student: 'student',
  thrift_savings_plan: 'thrift savings plan',
  tfsa: 'tfsa',
  trust: 'trust',
  ugma: 'ugma',
  utma: 'utma',
  variable_annuity: 'variable annuity',
} as const;
