/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type CreateAnalysisRuleDtoOneOfType =
  (typeof CreateAnalysisRuleDtoOneOfType)[keyof typeof CreateAnalysisRuleDtoOneOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAnalysisRuleDtoOneOfType = {
  exclude: 'exclude',
} as const
