/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateManualAccountDtoType = {
  investment: 'investment',
  credit: 'credit',
  depository: 'depository',
  loan: 'loan',
  brokerage: 'brokerage',
  other: 'other',
  crypto_wallet: 'crypto_wallet',
} as const
