/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CreateAnalysisRuleDtoOneOfThreeType } from './createAnalysisRuleDtoOneOfThreeType'
import type { AnalysisCategoryScope } from './analysisCategoryScope'

export type CreateAnalysisRuleDtoOneOfThree = {
  /**
   * @minLength 1
   * @maxLength 80
   */
  name: string
  type: CreateAnalysisRuleDtoOneOfThreeType
  inflowScope: AnalysisCategoryScope
  outflowScope: AnalysisCategoryScope
}
