/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CreateAccountDtoRawApiAccountType } from './createAccountDtoRawApiAccountType'
import type { CreateAccountDtoRawApiAccountSubType } from './createAccountDtoRawApiAccountSubType'
import type { MoneyWithSign } from './moneyWithSign'

/**
 * @nullable
 */
export type CreateAccountDtoRawApiAccount = {
  accountId: string
  name: string
  /** @nullable */
  mask: string | null
  type: CreateAccountDtoRawApiAccountType
  /** @nullable */
  subType: CreateAccountDtoRawApiAccountSubType
  availableBalance: MoneyWithSign
  currentBalance: MoneyWithSign
} | null
