/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign';
import type { CreateBalanceSnapshotDtoSnapshotType } from './createBalanceSnapshotDtoSnapshotType';

export interface CreateBalanceSnapshotDto {
  accountId: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  snapshotDate: string;
  currentBalance: MoneyWithSign;
  availableBalance: MoneyWithSign;
  snapshotType: CreateBalanceSnapshotDtoSnapshotType;
}
