/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CreateAccountDtoRawApiAccount } from './createAccountDtoRawApiAccount'
import type { CreateAccountDtoSubType } from './createAccountDtoSubType'
import type { CreateAccountDtoType } from './createAccountDtoType'
import type { MoneyWithSign } from './moneyWithSign'

export interface CreateAccountDto {
  /** @nullable */
  name: string | null
  /** @nullable */
  mask?: string | null
  availableBalance: MoneyWithSign
  currentBalance: MoneyWithSign
  type: CreateAccountDtoType
  /** @nullable */
  subType: CreateAccountDtoSubType
  /** @nullable */
  externalAccountId?: string | null
  /** @nullable */
  bankLinkId?: string | null
  /** @nullable */
  rawApiAccount?: CreateAccountDtoRawApiAccount
}
