/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CreateBalanceSnapshotDtoSnapshotType } from './createBalanceSnapshotDtoSnapshotType'
import type { MoneyWithSign } from './moneyWithSign'

export interface CreateBalanceSnapshotDto {
  accountId: string
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  snapshotDate: string
  snapshotType: CreateBalanceSnapshotDtoSnapshotType
  availableBalance: MoneyWithSign
  currentBalance: MoneyWithSign
}
