/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CreateAnalysisRuleDtoOneOfType } from './createAnalysisRuleDtoOneOfType'
import type { AnalysisCategoryScope } from './analysisCategoryScope'

export type CreateAnalysisRuleDtoOneOf = {
  /**
   * @minLength 1
   * @maxLength 80
   */
  name: string
  type: CreateAnalysisRuleDtoOneOfType
  excludeScope: AnalysisCategoryScope
}
