/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type DashboardAccountSummaryValuationMode =
  (typeof DashboardAccountSummaryValuationMode)[keyof typeof DashboardAccountSummaryValuationMode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardAccountSummaryValuationMode = {
  balance: 'balance',
  holdings: 'holdings',
} as const
