/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type DashboardPeriod =
  (typeof DashboardPeriod)[keyof typeof DashboardPeriod]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardPeriod = {
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
  threeYears: 'threeYears',
  fiveYears: 'fiveYears',
  tenYears: 'tenYears',
  all: 'all',
} as const
