/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { TimePeriod } from './timePeriod';
import type { NetWorthChartPoint } from './netWorthChartPoint';
import type { AccountSummary } from './accountSummary';

export interface DashboardSummary {
  netWorth: number;
  currency: string;
  /** @nullable */
  changePercent: number | null;
  comparisonPeriod: TimePeriod;
  chartData: NetWorthChartPoint[];
  assets: AccountSummary[];
  liabilities: AccountSummary[];
}
