/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { DashboardAccountSummaryType } from './dashboardAccountSummaryType'
import type { DashboardAccountSummaryValuationMode } from './dashboardAccountSummaryValuationMode'
import type { MoneyWithSign } from './moneyWithSign'

export interface DashboardAccountSummary {
  id: string
  name: string
  /** @nullable */
  customName: string | null
  type: (typeof DashboardAccountSummaryType)[keyof typeof DashboardAccountSummaryType]
  /** @nullable */
  subType: string | null
  valuationMode: DashboardAccountSummaryValuationMode
  /** @nullable */
  institutionName: string | null
  /** @nullable */
  archivedAt: string | null
  /** @nullable */
  syncedAt: string | null
  effectiveBalance: MoneyWithSign
  convertedEffectiveBalance?: MoneyWithSign
  changeAmount?: MoneyWithSign
  changePercent?: number
}
