/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { DashboardPeriod } from './dashboardPeriod'
import type { MoneyWithSign } from './moneyWithSign'
import type { DashboardAccountSummary } from './dashboardAccountSummary'

export interface DashboardSummaryResponse {
  period: DashboardPeriod
  startDate: string
  endDate: string
  reportingCurrency: string
  generatedAt: string
  netWorth: MoneyWithSign
  changeAmount: MoneyWithSign
  changePercent?: number
  assets: DashboardAccountSummary[]
  liabilities: DashboardAccountSummary[]
}
