/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { DashboardControllerGetSummaryPeriod } from './dashboardControllerGetSummaryPeriod';

export type DashboardControllerGetSummaryParams = {
/**
 * Time period for comparison (day, week, month, year). Defaults to month.
 */
period?: DashboardControllerGetSummaryPeriod;
};
