/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleCondition } from './categorizationRuleCondition'

export interface EditCategorizationRuleDto {
  /**
   * @minLength 1
   * @maxLength 80
   */
  name?: string
  priority?: number
  targetCategoryId?: string
  /** @minItems 1 */
  conditions?: CategorizationRuleCondition[]
}
