/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type InitiateLinkRequestNetwork = typeof InitiateLinkRequestNetwork[keyof typeof InitiateLinkRequestNetwork];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InitiateLinkRequestNetwork = {
  ethereum: 'ethereum',
  bitcoin: 'bitcoin',
} as const;
