/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { InvestmentActivityProvider } from './investmentActivityProvider'
import type { MoneyWithSign } from './moneyWithSign'
import type { InvestmentActivitySecurity } from './investmentActivitySecurity'

export interface InvestmentActivity {
  id: string
  activityId: string
  accountId: string
  /** @nullable */
  accountName: string | null
  provider: InvestmentActivityProvider
  /** @nullable */
  externalActivityId: string | null
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  activityDate: string
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  providerDate: string
  /** @nullable */
  providerDatetime: string | null
  amount: MoneyWithSign
  security: InvestmentActivitySecurity
  /** @nullable */
  externalSecurityId: string | null
  name: string
  providerDescription: string
  quantity: string
  price: string
  /** @nullable */
  fees: string | null
  investmentType: string
  investmentSubtype: string
  /** @nullable */
  cancelExternalActivityId: string | null
}
