/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { InvestmentSecurityProvider } from './investmentSecurityProvider'

export interface InvestmentSecurity {
  id: string
  provider: InvestmentSecurityProvider
  externalSecurityId: string
  /** @nullable */
  institutionId: string | null
  /** @nullable */
  institutionSecurityId: string | null
  /** @nullable */
  name: string | null
  /** @nullable */
  tickerSymbol: string | null
  /** @nullable */
  isin: string | null
  /** @nullable */
  cusip: string | null
  /** @nullable */
  sedol: string | null
  /** @nullable */
  type: string | null
  /** @nullable */
  subtype: string | null
  /** @nullable */
  isCashEquivalent: boolean | null
  /** @nullable */
  closePrice: string | null
  /** @nullable */
  closePriceAsOf: string | null
  /** @nullable */
  updateDatetime: string | null
  /** @nullable */
  isoCurrencyCode: string | null
  /** @nullable */
  unofficialCurrencyCode: string | null
  /** @nullable */
  marketIdentifierCode: string | null
  /** @nullable */
  sector: string | null
  /** @nullable */
  industry: string | null
  createdAt: string
  updatedAt: string
  userId: string
}
