/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type InvestmentSecurityProvider =
  (typeof InvestmentSecurityProvider)[keyof typeof InvestmentSecurityProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvestmentSecurityProvider = {
  plaid: 'plaid',
  yahoo: 'yahoo',
} as const
