/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { InvestmentHoldingSnapshotProvider } from './investmentHoldingSnapshotProvider'
import type { InvestmentSecurity } from './investmentSecurity'

export interface InvestmentHoldingSnapshot {
  id: string
  accountId: string
  securityId: string
  provider: InvestmentHoldingSnapshotProvider
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  snapshotDate: string
  /** @nullable */
  quantity: string | null
  /** @nullable */
  costBasis: string | null
  /** @nullable */
  institutionPrice: string | null
  /** @nullable */
  institutionPriceAsOf: string | null
  /** @nullable */
  institutionPriceDatetime: string | null
  /** @nullable */
  institutionValue: string | null
  /** @nullable */
  isoCurrencyCode: string | null
  /** @nullable */
  unofficialCurrencyCode: string | null
  /** @nullable */
  vestedQuantity: string | null
  /** @nullable */
  vestedValue: string | null
  security: InvestmentSecurity
  createdAt: string
  updatedAt: string
  userId: string
}
