/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type InvestmentHoldingSnapshotProvider =
  (typeof InvestmentHoldingSnapshotProvider)[keyof typeof InvestmentHoldingSnapshotProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvestmentHoldingSnapshotProvider = {
  plaid: 'plaid',
  manual: 'manual',
} as const
