/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { InvestmentTransactionProviderPayload } from './investmentTransactionProviderPayload'

export interface InvestmentTransaction {
  id: string
  activityId: string
  /** @nullable */
  securityId: string | null
  /** @nullable */
  externalSecurityId: string | null
  name: string
  quantity: string
  price: string
  /** @nullable */
  fees: string | null
  investmentType: string
  investmentSubtype: string
  /** @nullable */
  cancelExternalActivityId: string | null
  /** @nullable */
  providerPayload: InvestmentTransactionProviderPayload
  createdAt: string
  updatedAt: string
  userId: string
}
