/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface InvestmentActivityQuery {
  accountId?: string
  startDate?: string
  endDate?: string
  type?: string
  subtype?: string
  /**
   * @minimum 0
   * @nullable
   */
  pageIndex?: number | null
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number
}
