/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { InvestmentHoldingsResponseAccountValue } from './investmentHoldingsResponseAccountValue'
import type { InvestmentHoldingSnapshot } from './investmentHoldingSnapshot'

export interface InvestmentHoldingsResponse {
  accountId: string
  /**
   * @nullable
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  snapshotDate: string | null
  /** @nullable */
  accountCurrency: string | null
  accountValue: InvestmentHoldingsResponseAccountValue
  holdings: InvestmentHoldingSnapshot[]
}
