/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { LLMProjectionPlanResponseVersion } from './lLMProjectionPlanResponseVersion'
import type { ProjectionScenario } from './projectionScenario'

export interface LLMProjectionPlanResponse {
  version: LLMProjectionPlanResponseVersion
  assistantMessage: string
  scenario: ProjectionScenario
  followUpQuestions: string[]
  warnings: string[]
}
