/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type LLMProjectionPlanResponseVersion =
  (typeof LLMProjectionPlanResponseVersion)[keyof typeof LLMProjectionPlanResponseVersion]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LLMProjectionPlanResponseVersion = {
  NUMBER_1: 1,
} as const
