/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface ManualBrokeragePositionInput {
  /**
   * @minLength 1
   * @maxLength 32
   */
  symbol: string
  /** @pattern ^(?:0|[1-9]\d{0,17})(?:\.\d{1,12})?$ */
  quantity: string
}
