/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface MarketSecuritySearchQuery {
  /**
   * @minLength 2
   * @maxLength 100
   */
  query: string
  /**
   * @minimum 1
   * @maximum 20
   */
  limit?: number
}
