/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type MarketSecuritySearchResultQuoteType =
  (typeof MarketSecuritySearchResultQuoteType)[keyof typeof MarketSecuritySearchResultQuoteType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketSecuritySearchResultQuoteType = {
  EQUITY: 'EQUITY',
  ETF: 'ETF',
} as const
