/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { Money } from './money';
import type { MoneyWithSignSign } from './moneyWithSignSign';

export interface MoneyWithSign {
  money: Money;
  sign: MoneyWithSignSign;
}
