/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface Money {
  /** @minLength 1 */
  currency: string
  /** @pattern ^(0|[1-9]\d{0,77})$ */
  amount: string
}
