/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { NetWorthChartPointValue } from './netWorthChartPointValue'

export interface NetWorthChartPoint {
  date: string
  value: NetWorthChartPointValue
}
