/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface NotificationInboxQuery {
  /** @maxLength 512 */
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number
}
