/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { NotificationType } from './notificationType'
import type { NotificationPayload } from './notificationPayload'
import type { NotificationStatus } from './notificationStatus'

export interface Notification {
  id: string
  type: NotificationType
  dedupeKey: string
  payload: NotificationPayload
  status: NotificationStatus
  /** @nullable */
  readAt: string | null
  /** @nullable */
  archivedAt: string | null
  createdAt: string
  updatedAt: string
  userId: string
}
