/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type NotificationInboxItemType =
  (typeof NotificationInboxItemType)[keyof typeof NotificationInboxItemType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationInboxItemType = {
  transactionsnew_synced: 'transactions.new_synced',
  bank_linkneeds_attention: 'bank_link.needs_attention',
} as const
