/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface NotificationSummary {
  /** @minimum 0 */
  uncategorizedTransactionCount: number
  /** @minimum 0 */
  unreadNotificationCount: number
  computedAt: string
}
