/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { NotificationInboxItem } from './notificationInboxItem'

export interface NotificationInboxPage {
  items: NotificationInboxItem[]
  /** @nullable */
  nextCursor: string | null
  hasMore: boolean
}
