/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type NotificationType =
  (typeof NotificationType)[keyof typeof NotificationType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationType = {
  transactionsnew_synced: 'transactions.new_synced',
  systemtest: 'system.test',
} as const
