/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type NotificationPayloadAnyOfTwoStatus =
  (typeof NotificationPayloadAnyOfTwoStatus)[keyof typeof NotificationPayloadAnyOfTwoStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationPayloadAnyOfTwoStatus = {
  ERROR: 'ERROR',
  PENDING_REAUTH: 'PENDING_REAUTH',
} as const
