/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type NotificationStatus =
  (typeof NotificationStatus)[keyof typeof NotificationStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationStatus = {
  active: 'active',
  archived: 'archived',
} as const
