/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { NotificationPayloadAnyOf } from './notificationPayloadAnyOf'
import type { NotificationPayloadAnyOfTwo } from './notificationPayloadAnyOfTwo'
import type { NotificationPayloadAnyOfFive } from './notificationPayloadAnyOfFive'

export type NotificationPayload =
  | NotificationPayloadAnyOf
  | NotificationPayloadAnyOfTwo
  | NotificationPayloadAnyOfFive
