/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type NotificationPayloadAnyOf = {
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  count: number
  /** @minItems 1 */
  transactionIds: string[]
  /** @minItems 1 */
  accountIds: string[]
  occurredAt: string
}
