/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { Transaction } from './transaction'

export interface PaginatedTransactions {
  data: Array<Transaction>
  total: number
  page: number
  limit: number
  hasMore: boolean
}
