/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { Transaction } from './transaction'

export interface PaginatedTransactionResponse {
  data: Transaction[]
  /** @nullable */
  total: number | null
  /** @nullable */
  pageIndex: number | null
  /** @nullable */
  nextCursor: string | null
  hasMore: boolean
  pageSize: number
}
