/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategorizationRuleCondition } from './categorizationRuleCondition'

export interface PreviewCategorizationRuleDraftDto {
  targetCategoryId: string
  priority?: number
  /** @minItems 1 */
  conditions: CategorizationRuleCondition[]
}
