/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ApplyCategorizationRuleResponse } from './applyCategorizationRuleResponse'
import type { PreviewCategorizationRuleApplicationResponseAllOf } from './previewCategorizationRuleApplicationResponseAllOf'

export type PreviewCategorizationRuleApplicationResponse =
  ApplyCategorizationRuleResponse &
    PreviewCategorizationRuleApplicationResponseAllOf
