/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface ProjectionPoint {
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  date: string
  historical?: number
  projectedMedian?: number
  projectedLow?: number
  projectedHigh?: number
  totalContributions: number
}
