/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type ProjectionScopeOneOfThreeAccountGroupingsItem =
  (typeof ProjectionScopeOneOfThreeAccountGroupingsItem)[keyof typeof ProjectionScopeOneOfThreeAccountGroupingsItem]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectionScopeOneOfThreeAccountGroupingsItem = {
  cash: 'cash',
  credit: 'credit',
  investment: 'investment',
  liability: 'liability',
} as const
