/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type ProjectionChartAnnotationKind =
  (typeof ProjectionChartAnnotationKind)[keyof typeof ProjectionChartAnnotationKind]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectionChartAnnotationKind = {
  milestone: 'milestone',
  assumption: 'assumption',
  contribution: 'contribution',
  risk: 'risk',
} as const
