/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionControlSpecOneOfNineKind } from './projectionControlSpecOneOfNineKind'

export type ProjectionControlSpecOneOfNine = {
  /** @minLength 1 */
  id: string
  /** @minLength 1 */
  label: string
  /** @minLength 1 */
  parameterPath: string
  kind: ProjectionControlSpecOneOfNineKind
}
