/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionScenario } from './projectionScenario'

export interface ProjectionPlanRequest {
  /**
   * @minLength 1
   * @maxLength 4000
   */
  prompt: string
  currentScenario?: ProjectionScenario
  /**
   * @minimum 0
   * @maximum 20
   */
  historyWindowYears?: number
}
