/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionChartAnnotationKind } from './projectionChartAnnotationKind'

export interface ProjectionChartAnnotation {
  /** @minLength 1 */
  id: string
  kind: ProjectionChartAnnotationKind
  /** @minLength 1 */
  label: string
  description?: string
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  date?: string
  value?: number
}
