/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionScopeOneOf } from './projectionScopeOneOf'
import type { ProjectionScopeOneOfThree } from './projectionScopeOneOfThree'
import type { ProjectionScopeOneOfSix } from './projectionScopeOneOfSix'

export type ProjectionScope =
  | ProjectionScopeOneOf
  | ProjectionScopeOneOfThree
  | ProjectionScopeOneOfSix
