/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionScope } from './projectionScope'
import type { ProjectionScenarioCadence } from './projectionScenarioCadence'
import type { ProjectionScenarioParameters } from './projectionScenarioParameters'
import type { ProjectionAssumption } from './projectionAssumption'
import type { ProjectionControlSpec } from './projectionControlSpec'
import type { ProjectionChartAnnotation } from './projectionChartAnnotation'

export interface ProjectionScenario {
  /** @minLength 1 */
  id: string
  /** @minLength 1 */
  title: string
  prompt?: string
  /**
   * @minLength 3
   * @maxLength 10
   */
  currency: string
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  startDate: string
  scope: ProjectionScope
  /**
   * @minimum 1
   * @maximum 50
   */
  horizonYears: number
  cadence: ProjectionScenarioCadence
  parameters: ProjectionScenarioParameters
  assumptions: ProjectionAssumption[]
  controls: ProjectionControlSpec[]
  annotations: ProjectionChartAnnotation[]
}
