/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type ProjectionScopeOneOfKind =
  (typeof ProjectionScopeOneOfKind)[keyof typeof ProjectionScopeOneOfKind]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectionScopeOneOfKind = {
  netWorth: 'netWorth',
} as const
