/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionScope } from './projectionScope'

export interface ProjectionAnnualContribution {
  /** @minLength 1 */
  id: string
  /** @minLength 1 */
  label: string
  amount: number
  /**
   * @minLength 3
   * @maxLength 10
   */
  currency: string
  target: ProjectionScope
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  startDate?: string
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  endDate?: string
  inflationAdjust?: boolean
}
