/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type ProjectionAssumptionSource =
  (typeof ProjectionAssumptionSource)[keyof typeof ProjectionAssumptionSource]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectionAssumptionSource = {
  user_prompt: 'user_prompt',
  llm_inferred: 'llm_inferred',
  default: 'default',
  system: 'system',
} as const
