/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionAssumptionSource } from './projectionAssumptionSource'

export interface ProjectionAssumption {
  /** @minLength 1 */
  id: string
  /** @minLength 1 */
  label: string
  /** @minLength 1 */
  valueLabel: string
  source: ProjectionAssumptionSource
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence?: number
  parameterPath?: string
}
