/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionScopeOneOfThreeKind } from './projectionScopeOneOfThreeKind'
import type { ProjectionScopeOneOfThreeAccountGroupingsItem } from './projectionScopeOneOfThreeAccountGroupingsItem'

export type ProjectionScopeOneOfThree = {
  kind: ProjectionScopeOneOfThreeKind
  /** @minItems 1 */
  accountGroupings: ProjectionScopeOneOfThreeAccountGroupingsItem[]
}
