/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionControlSpecOneOfFiveOptionsItemValue } from './projectionControlSpecOneOfFiveOptionsItemValue'

export type ProjectionControlSpecOneOfFiveOptionsItem = {
  /** @minLength 1 */
  label: string
  value: ProjectionControlSpecOneOfFiveOptionsItemValue
}
