/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionControlSpecOneOf } from './projectionControlSpecOneOf'
import type { ProjectionControlSpecOneOfThree } from './projectionControlSpecOneOfThree'
import type { ProjectionControlSpecOneOfFive } from './projectionControlSpecOneOfFive'
import type { ProjectionControlSpecOneOfNine } from './projectionControlSpecOneOfNine'

export type ProjectionControlSpec =
  | ProjectionControlSpecOneOf
  | ProjectionControlSpecOneOfThree
  | ProjectionControlSpecOneOfFive
  | ProjectionControlSpecOneOfNine
