/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionControlSpecOneOfThreeKind } from './projectionControlSpecOneOfThreeKind'

export type ProjectionControlSpecOneOfThree = {
  /** @minLength 1 */
  id: string
  /** @minLength 1 */
  label: string
  /** @minLength 1 */
  parameterPath: string
  kind: ProjectionControlSpecOneOfThreeKind
  min: number
  max: number
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  step: number
}
