/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type ProjectionControlSpecOneOfFiveKind =
  (typeof ProjectionControlSpecOneOfFiveKind)[keyof typeof ProjectionControlSpecOneOfFiveKind]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectionControlSpecOneOfFiveKind = {
  segmentedSelect: 'segmentedSelect',
} as const
