/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionAnnualContribution } from './projectionAnnualContribution'

export type ProjectionScenarioParameters = {
  currentValue?: number
  annualContributions: ProjectionAnnualContribution[]
  /**
   * @minimum -0.5
   * @maximum 0.5
   */
  expectedAnnualReturn: number
  /**
   * @minimum 0
   * @maximum 0.25
   */
  inflationRate: number
  /**
   * @minimum 0
   * @maximum 0.5
   */
  taxDragRate: number
  /**
   * @minimum 0
   * @maximum 1
   */
  volatility: number
}
