/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionPoint } from './projectionPoint'
import type { ProjectionMetric } from './projectionMetric'
import type { ProjectionMilestone } from './projectionMilestone'
import type { ProjectionChartAnnotation } from './projectionChartAnnotation'

export interface ProjectionResult {
  scenarioId: string
  currency: string
  points: ProjectionPoint[]
  metrics: ProjectionMetric[]
  milestones: ProjectionMilestone[]
  annotations: ProjectionChartAnnotation[]
}
