/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProjectionScopeOneOfSixKind } from './projectionScopeOneOfSixKind'

export type ProjectionScopeOneOfSix = {
  kind: ProjectionScopeOneOfSixKind
  /** @minItems 1 */
  accountIds: string[]
}
