/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type ProjectionScopeOneOfSixKind =
  (typeof ProjectionScopeOneOfSixKind)[keyof typeof ProjectionScopeOneOfSixKind]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectionScopeOneOfSixKind = {
  accounts: 'accounts',
} as const
