/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { ProviderCategoryHintProvider } from './providerCategoryHintProvider'

export interface ProviderCategoryHint {
  provider: ProviderCategoryHintProvider
  /** @nullable */
  primary: string | null
  /** @nullable */
  detailed: string | null
  /** @nullable */
  displayLabel: string | null
  /** @nullable */
  confidenceLevel: string | null
  /** @nullable */
  iconUrl: string | null
}
