/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type ProviderCategoryHintProvider =
  (typeof ProviderCategoryHintProvider)[keyof typeof ProviderCategoryHintProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProviderCategoryHintProvider = {
  plaid: 'plaid',
} as const
