/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type RateWithSourceRatio = {
  /** @pattern ^[1-9]\d*$ */
  numerator: string
  /** @pattern ^[1-9]\d*$ */
  denominator: string
}
