/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type RateWithSourceSource =
  (typeof RateWithSourceSource)[keyof typeof RateWithSourceSource]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RateWithSourceSource = {
  DB: 'DB',
  FORWARD_FILLED: 'FORWARD_FILLED',
  BACKWARD_FILLED: 'BACKWARD_FILLED',
  IDENTITY: 'IDENTITY',
} as const
