/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { RateWithSourceSource } from './rateWithSourceSource'
import type { RateWithSourceRatio } from './rateWithSourceRatio'

export interface RateWithSource {
  baseCurrency: string
  targetCurrency: string
  requestedDate: string
  rateDate: string
  /**
   * @maxLength 220
   * @pattern ^(0|[1-9]\d*)(\.\d+)?$
   */
  rate: string
  source: RateWithSourceSource
  ratio: RateWithSourceRatio
}
