/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type RecurringManualTransactionFrequency =
  (typeof RecurringManualTransactionFrequency)[keyof typeof RecurringManualTransactionFrequency]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecurringManualTransactionFrequency = {
  monthly: 'monthly',
} as const
