/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface RecurringManualTransactionOccurrence {
  id: string
  scheduleId: string
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  occurrenceDate: string
  transactionId: string
  /** @nullable */
  generatedAt: string | null
  createdAt: string
  updatedAt: string
  userId: string
}
