/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type RegisterPushSubscriptionDtoProtocolVersion =
  (typeof RegisterPushSubscriptionDtoProtocolVersion)[keyof typeof RegisterPushSubscriptionDtoProtocolVersion]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterPushSubscriptionDtoProtocolVersion = {
  NUMBER_2: 2,
} as const
