/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { RegisterPushSubscriptionDtoProtocolVersion } from './registerPushSubscriptionDtoProtocolVersion'
import type { RegisterPushSubscriptionDtoKeys } from './registerPushSubscriptionDtoKeys'

export interface RegisterPushSubscriptionDto {
  protocolVersion: RegisterPushSubscriptionDtoProtocolVersion
  endpoint: string
  /** @nullable */
  expirationTime?: number | null
  keys: RegisterPushSubscriptionDtoKeys
  /** @nullable */
  userAgent?: string | null
}
