/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type SanitizedBankLinkStatus =
  (typeof SanitizedBankLinkStatus)[keyof typeof SanitizedBankLinkStatus]

export const SanitizedBankLinkStatus = {
  OK: 'OK',
  ERROR: 'ERROR',
  PENDING_REAUTH: 'PENDING_REAUTH',
} as const
