/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { SanitizedBankLinkStatus } from './sanitizedBankLinkStatus';
import type { SanitizedBankLinkStatusBody } from './sanitizedBankLinkStatusBody';

export interface SanitizedBankLink {
  id: string;
  providerName: string;
  accountIds: string[];
  /** @nullable */
  institutionId?: string | null;
  /** @nullable */
  institutionName?: string | null;
  status: SanitizedBankLinkStatus;
  /** @nullable */
  statusDate: string | null;
  /** @nullable */
  statusBody?: SanitizedBankLinkStatusBody;
  createdAt: string;
  updatedAt: string;
  userId: string;
}
