/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TimePeriod = typeof TimePeriod[keyof typeof TimePeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimePeriod = {
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
} as const;
