/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { TransactionAnalysisControllerGetBalanceAdjustmentsFlowDirection } from './transactionAnalysisControllerGetBalanceAdjustmentsFlowDirection'
import type { TransactionAnalysisControllerGetBalanceAdjustmentsCategoryPrimary } from './transactionAnalysisControllerGetBalanceAdjustmentsCategoryPrimary'

export type TransactionAnalysisControllerGetBalanceAdjustmentsParams = {
  /**
   * Whether to return inflow or outflow balance adjustments
   */
  flowDirection: TransactionAnalysisControllerGetBalanceAdjustmentsFlowDirection
  /**
   * Primary category filter. Must be BALANCE_ADJUSTMENT.
   */
  categoryPrimary: TransactionAnalysisControllerGetBalanceAdjustmentsCategoryPrimary
  /**
   * Activity end date (YYYY-MM-DD, inclusive)
   */
  endDate: string
  /**
   * Activity start date (YYYY-MM-DD, inclusive)
   */
  startDate: string
}
