/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { TransactionAnalysisTransactionsQueryFlowDirection } from './transactionAnalysisTransactionsQueryFlowDirection'

export interface TransactionAnalysisTransactionsQuery {
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  startDate: string
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  endDate: string
  categoryPrimary: string
  flowDirection: TransactionAnalysisTransactionsQueryFlowDirection
}
