/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionControllerFindAllParams = {
  page?: number
  limit?: number
  accountId?: string | Array<string>
  categoryId?: string | Array<string>
  startDate?: string
  endDate?: string
  search?: string
  minAmount?: number
  maxAmount?: number
}
