/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { TransactionControllerFindAllAmountSign } from './transactionControllerFindAllAmountSign'
import type { TransactionControllerFindAllCategoryReviewStatus } from './transactionControllerFindAllCategoryReviewStatus'

export type TransactionControllerFindAllParams = {
  /**
   * Page index (0-based)
   */
  pageIndex?: string
  /**
   * Page size
   */
  pageSize?: string
  /**
   * Sort column (activityDate, merchantName, pending, amount)
   */
  sortBy?: string
  /**
   * Sort order (ASC or DESC)
   */
  sortOrder?: string
  /**
   * Filter by account ID
   */
  accountId?: string
  /**
   * Filter by activity start date (YYYY-MM-DD)
   */
  startDate?: string
  /**
   * Filter by activity end date (YYYY-MM-DD)
   */
  endDate?: string
  /**
   * Filter by primary category (e.g. FOOD_AND_DRINK, UNCATEGORIZED)
   */
  categoryPrimary?: string
  /**
   * Filter by amount sign (positive or negative)
   */
  amountSign?: TransactionControllerFindAllAmountSign
  /**
   * When true, adds convertedAmount in user preferred currency to each transaction
   */
  convert?: boolean
  /**
   * Filter by category review status
   */
  categoryReviewStatus?: TransactionControllerFindAllCategoryReviewStatus
}
