/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionAnalysisBalanceAdjustmentsQueryCategoryPrimary =
  (typeof TransactionAnalysisBalanceAdjustmentsQueryCategoryPrimary)[keyof typeof TransactionAnalysisBalanceAdjustmentsQueryCategoryPrimary]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionAnalysisBalanceAdjustmentsQueryCategoryPrimary = {
  BALANCE_ADJUSTMENT: 'BALANCE_ADJUSTMENT',
} as const
