/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategoryAggregate } from './categoryAggregate'
import type { BalanceAdjustment } from './balanceAdjustment'

export interface TransactionAnalysisResponse {
  startDate: string
  endDate: string
  currency: string
  inflows: CategoryAggregate[]
  outflows: CategoryAggregate[]
  totalInflow: number
  totalOutflow: number
  netFlow: number
  uncategorizedInflow: number
  uncategorizedOutflow: number
  balanceAdjustments: BalanceAdjustment[]
}
