/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign'
import type { TransactionCategory } from './transactionCategory'
import type { TransactionConvertedAmount } from './transactionConvertedAmount'

export interface Transaction {
  id: string
  amount: MoneyWithSign
  accountId: string
  /** @nullable */
  merchantName: string | null
  pending: boolean
  /** @nullable */
  externalTransactionId: string | null
  /** @nullable */
  logoUrl: string | null
  date: string
  /** @nullable */
  datetime: string | null
  /** @nullable */
  authorizedDate: string | null
  /** @nullable */
  authorizedDatetime: string | null
  /** @nullable */
  categoryId: string | null
  category?: TransactionCategory
  /** @nullable */
  accountName?: string | null
  convertedAmount?: TransactionConvertedAmount
  createdAt: string
  updatedAt: string
  userId: string
}
