/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { TransactionAnalysisControllerGetTransactionsFlowDirection } from './transactionAnalysisControllerGetTransactionsFlowDirection'

export type TransactionAnalysisControllerGetTransactionsParams = {
  /**
   * Whether to return positive or negative unmatched transactions
   */
  flowDirection: TransactionAnalysisControllerGetTransactionsFlowDirection
  /**
   * Primary category to drill into (for example FOOD_AND_DRINK or UNCATEGORIZED)
   */
  categoryPrimary: string
  /**
   * End date (YYYY-MM-DD, inclusive)
   */
  endDate: string
  /**
   * Start date (YYYY-MM-DD, inclusive)
   */
  startDate: string
}
