/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionAnalysisControllerGetTransactionsFlowDirection =
  (typeof TransactionAnalysisControllerGetTransactionsFlowDirection)[keyof typeof TransactionAnalysisControllerGetTransactionsFlowDirection]

export const TransactionAnalysisControllerGetTransactionsFlowDirection = {
  inflow: 'inflow',
  outflow: 'outflow',
} as const
