/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionAnalysisControllerGetBalanceAdjustmentsFlowDirection =
  (typeof TransactionAnalysisControllerGetBalanceAdjustmentsFlowDirection)[keyof typeof TransactionAnalysisControllerGetBalanceAdjustmentsFlowDirection]

export const TransactionAnalysisControllerGetBalanceAdjustmentsFlowDirection = {
  inflow: 'inflow',
  outflow: 'outflow',
} as const
