/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionControllerFindAllAmountSign =
  (typeof TransactionControllerFindAllAmountSign)[keyof typeof TransactionControllerFindAllAmountSign]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionControllerFindAllAmountSign = {
  positive: 'positive',
  negative: 'negative',
} as const
