/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionAnalysisTransactionsQueryFlowDirection =
  (typeof TransactionAnalysisTransactionsQueryFlowDirection)[keyof typeof TransactionAnalysisTransactionsQueryFlowDirection]

export const TransactionAnalysisTransactionsQueryFlowDirection = {
  inflow: 'inflow',
  outflow: 'outflow',
} as const
