/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisAuditExcludedRow } from './analysisAuditExcludedRow'
import type { AnalysisAuditNeutralizedRow } from './analysisAuditNeutralizedRow'

export type TransactionAnalysisAuditResponseRowsItem =
  | AnalysisAuditExcludedRow
  | AnalysisAuditNeutralizedRow
