/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionSource =
  (typeof TransactionSource)[keyof typeof TransactionSource]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionSource = {
  provider: 'provider',
  manual: 'manual',
} as const
