/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionControllerFindAllCategoryReviewStatus =
  (typeof TransactionControllerFindAllCategoryReviewStatus)[keyof typeof TransactionControllerFindAllCategoryReviewStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionControllerFindAllCategoryReviewStatus = {
  needs_review: 'needs_review',
  reviewed: 'reviewed',
} as const
