/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionControllerGetSummaryCategoryReviewStatus =
  (typeof TransactionControllerGetSummaryCategoryReviewStatus)[keyof typeof TransactionControllerGetSummaryCategoryReviewStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionControllerGetSummaryCategoryReviewStatus = {
  needs_review: 'needs_review',
  reviewed: 'reviewed',
} as const
