/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { TransactionControllerGetSummaryAmountSign } from './transactionControllerGetSummaryAmountSign'
import type { TransactionControllerGetSummaryCategoryReviewStatus } from './transactionControllerGetSummaryCategoryReviewStatus'

export type TransactionControllerGetSummaryParams = {
  /**
   * Filter by account ID
   */
  accountId?: string
  /**
   * Filter by activity start date (YYYY-MM-DD)
   */
  startDate?: string
  /**
   * Filter by activity end date (YYYY-MM-DD)
   */
  endDate?: string
  /**
   * Filter by primary category (e.g. FOOD_AND_DRINK, UNCATEGORIZED)
   */
  categoryPrimary?: string
  /**
   * Filter by amount sign (positive or negative)
   */
  amountSign?: TransactionControllerGetSummaryAmountSign
  /**
   * When false, still returns preferred-currency totals for stable frontend display
   */
  convert?: boolean
  /**
   * Filter by category review status
   */
  categoryReviewStatus?: TransactionControllerGetSummaryCategoryReviewStatus
}
