/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionAnalysisControllerGetBalanceAdjustmentsCategoryPrimary =
  (typeof TransactionAnalysisControllerGetBalanceAdjustmentsCategoryPrimary)[keyof typeof TransactionAnalysisControllerGetBalanceAdjustmentsCategoryPrimary]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionAnalysisControllerGetBalanceAdjustmentsCategoryPrimary =
  {
    BALANCE_ADJUSTMENT: 'BALANCE_ADJUSTMENT',
  } as const
