/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign';

export interface Transaction {
  id: string;
  amount: MoneyWithSign;
  accountId: string;
  /** @nullable */
  merchantName: string | null;
  pending: boolean;
  /** @nullable */
  externalTransactionId: string | null;
  /** @nullable */
  logoUrl: string | null;
  date: string;
  /** @nullable */
  datetime: string | null;
  /** @nullable */
  authorizedDate: string | null;
  /** @nullable */
  authorizedDatetime: string | null;
  /** @nullable */
  categoryId: string | null;
  createdAt: string;
  updatedAt: string;
  userId: string;
}
