/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionCategoryReviewMethod =
  (typeof TransactionCategoryReviewMethod)[keyof typeof TransactionCategoryReviewMethod]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionCategoryReviewMethod = {
  manual_accept: 'manual_accept',
  manual_change: 'manual_change',
  bulk_accept: 'bulk_accept',
} as const
