/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategoryAggregate } from './categoryAggregate'

export interface TransactionAnalysisResponse {
  startDate: string
  endDate: string
  currency: string
  inflows: Array<CategoryAggregate>
  outflows: Array<CategoryAggregate>
  totalInflow: number
  totalOutflow: number
  netFlow: number
  uncategorizedInflow: number
  uncategorizedOutflow: number
}
