/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign'

export interface TransactionSummary {
  currency: string
  inflow: MoneyWithSign
  outflow: MoneyWithSign
  net: MoneyWithSign
  transactionCount: number
  pendingCount: number
  uncategorizedCount: number
}
