/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { CategoryAggregate } from './categoryAggregate'

export interface TransactionAnalysisResponse {
  startDate: string
  endDate: string
  currency: string
  inflows: CategoryAggregate[]
  outflows: CategoryAggregate[]
  /** @pattern ^(0|[1-9]\d{0,77})$ */
  totalInflow: string
  /** @pattern ^(0|[1-9]\d{0,77})$ */
  totalOutflow: string
  /** @pattern ^(0|-?[1-9]\d{0,77})$ */
  netFlow: string
  /** @pattern ^(0|[1-9]\d{0,77})$ */
  uncategorizedInflow: string
  /** @pattern ^(0|[1-9]\d{0,77})$ */
  uncategorizedOutflow: string
}
