/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionControllerGetSummaryAmountSign =
  (typeof TransactionControllerGetSummaryAmountSign)[keyof typeof TransactionControllerGetSummaryAmountSign]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionControllerGetSummaryAmountSign = {
  positive: 'positive',
  negative: 'negative',
} as const
