/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionAnalysisControllerGetAuditParams = {
  /**
   * Activity end date (YYYY-MM-DD, inclusive)
   */
  endDate: string
  /**
   * Activity start date (YYYY-MM-DD, inclusive)
   */
  startDate: string
}
