/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type TransactionControllerFindAllParams = {
  /**
   * Page index (0-based)
   */
  pageIndex?: string
  /**
   * Page size
   */
  pageSize?: string
  /**
   * Sort column (date, merchantName, pending)
   */
  sortBy?: string
  /**
   * Sort order (ASC or DESC)
   */
  sortOrder?: string
  /**
   * Filter by account ID
   */
  accountId?: string
}
