/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type UpdateBalanceSnapshotDtoSnapshotType = typeof UpdateBalanceSnapshotDtoSnapshotType[keyof typeof UpdateBalanceSnapshotDtoSnapshotType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateBalanceSnapshotDtoSnapshotType = {
  USER_UPDATE: 'USER_UPDATE',
  SYNC: 'SYNC',
  FORWARD_FILL: 'FORWARD_FILL',
} as const;
