/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface UpdateAccountMetadataDto {
  /** @nullable */
  name?: string | null
  /** @nullable */
  customName?: string | null
  /** @nullable */
  notes?: string | null
}
