/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface UpdateExchangeRateDto {
  baseCurrency?: string
  targetCurrency?: string
  /**
   * @maxLength 156
   * @pattern ^-?(0|[1-9]\d*)(\.\d+)?$
   */
  rate?: string
  rateDate?: string
}
