/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign'

export interface UpdateManualBalanceDto {
  balance: MoneyWithSign
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  effectiveDate: string
  confirmHistoryReset?: boolean
}
