/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { AnalysisRuleType } from './analysisRuleType'
import type { AnalysisCategoryScope } from './analysisCategoryScope'

export interface UpdateAnalysisRuleDto {
  /**
   * @minLength 1
   * @maxLength 80
   */
  name?: string
  type?: AnalysisRuleType
  excludeScope?: AnalysisCategoryScope
  inflowScope?: AnalysisCategoryScope
  outflowScope?: AnalysisCategoryScope
  archived?: boolean
}
