/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserSettingsDtoTheme } from './updateUserSettingsDtoTheme'
import type { UpdateUserSettingsDtoNotifications } from './updateUserSettingsDtoNotifications'

export interface UpdateUserSettingsDto {
  currency?: string
  timezone?: string
  hideZeroBalanceAccounts?: boolean
  theme?: UpdateUserSettingsDtoTheme
  /**
   * @minimum 0
   * @maximum 180
   */
  neutralizationLookaroundDays?: number
  analysisSankeyEnabled?: boolean
  notifications?: UpdateUserSettingsDtoNotifications
}
