/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign';
import type { UpdateAccountDtoType } from './updateAccountDtoType';
import type { UpdateAccountDtoSubType } from './updateAccountDtoSubType';
import type { UpdateAccountDtoRawApiAccount } from './updateAccountDtoRawApiAccount';

export interface UpdateAccountDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  mask?: string | null;
  availableBalance?: MoneyWithSign;
  currentBalance?: MoneyWithSign;
  type?: UpdateAccountDtoType;
  /** @nullable */
  subType?: UpdateAccountDtoSubType;
  /** @nullable */
  externalAccountId?: string | null;
  /** @nullable */
  bankLinkId?: string | null;
  /** @nullable */
  rawApiAccount?: UpdateAccountDtoRawApiAccount;
}
