/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export type UpdateUserSettingsDtoTheme =
  (typeof UpdateUserSettingsDtoTheme)[keyof typeof UpdateUserSettingsDtoTheme]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserSettingsDtoTheme = {
  'splice-light': 'splice-light',
  'splice-dark': 'splice-dark',
  dracula: 'dracula',
  'oled-black': 'oled-black',
} as const
