/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { UpdateAccountDtoRawApiAccountType } from './updateAccountDtoRawApiAccountType'
import type { UpdateAccountDtoRawApiAccountSubType } from './updateAccountDtoRawApiAccountSubType'
import type { MoneyWithSign } from './moneyWithSign'

/**
 * @nullable
 */
export type UpdateAccountDtoRawApiAccount = {
  accountId: string
  name: string
  /** @nullable */
  mask: string | null
  type: UpdateAccountDtoRawApiAccountType
  /** @nullable */
  subType: UpdateAccountDtoRawApiAccountSubType
  availableBalance: MoneyWithSign
  currentBalance: MoneyWithSign
} | null
