/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */

export interface UpdateCustomCategoryDto {
  /**
   * @minLength 1
   * @maxLength 80
   */
  primary?: string
  /**
   * @minLength 1
   * @maxLength 120
   */
  detailed?: string
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null
  /** @pattern ^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ */
  color?: string
  archived?: boolean
}
