/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { MoneyWithSign } from './moneyWithSign'
import type { UpdateTransactionDtoCounterpartiesItem } from './updateTransactionDtoCounterpartiesItem'
import type { UpdateTransactionDtoLocation } from './updateTransactionDtoLocation'
import type { UpdateTransactionDtoPaymentMeta } from './updateTransactionDtoPaymentMeta'
import type { UpdateTransactionDtoProviderPayload } from './updateTransactionDtoProviderPayload'
import type { UpdateTransactionDtoPersonalFinanceCategory } from './updateTransactionDtoPersonalFinanceCategory'

export interface UpdateTransactionDto {
  amount?: MoneyWithSign
  accountId?: string
  /** @nullable */
  merchantName?: string | null
  /** @nullable */
  providerTransactionName?: string | null
  /** @nullable */
  originalDescription?: string | null
  pending?: boolean
  /** @nullable */
  pendingTransactionId?: string | null
  /** @nullable */
  accountOwner?: string | null
  /** @nullable */
  externalTransactionId?: string | null
  /** @nullable */
  logoUrl?: string | null
  /** @nullable */
  website?: string | null
  /** @nullable */
  merchantEntityId?: string | null
  /** @nullable */
  paymentChannel?: string | null
  /** @nullable */
  transactionCode?: string | null
  /** @nullable */
  personalFinanceCategoryIconUrl?: string | null
  /** @nullable */
  personalFinanceCategoryConfidenceLevel?: string | null
  /** @nullable */
  counterparties?: UpdateTransactionDtoCounterpartiesItem[] | null
  /** @nullable */
  location?: UpdateTransactionDtoLocation
  /** @nullable */
  paymentMeta?: UpdateTransactionDtoPaymentMeta
  /** @nullable */
  providerPayload?: UpdateTransactionDtoProviderPayload
  providerDate?: string
  /** @nullable */
  providerDatetime?: string | null
  /** @nullable */
  authorizedDate?: string | null
  /** @nullable */
  authorizedDatetime?: string | null
  /** @nullable */
  reportingDateOverride?: string | null
  /** @nullable */
  categoryId?: string | null
  personalFinanceCategory?: UpdateTransactionDtoPersonalFinanceCategory
}
