/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { UserSettingsNotificationsTransactions } from './userSettingsNotificationsTransactions'
import type { UserSettingsNotificationsBankLinks } from './userSettingsNotificationsBankLinks'

export type UserSettingsNotifications = {
  transactions?: UserSettingsNotificationsTransactions
  bankLinks?: UserSettingsNotificationsBankLinks
}
