/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { UserSettings } from './userSettings'
import type { UserProviderDetails } from './userProviderDetails'

export interface User {
  id: string
  email: string
  settings: UserSettings
  providerDetails?: UserProviderDetails
  createdAt: string
  updatedAt: string
}
