/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Splice API
 * Financial account management API
 * OpenAPI spec version: 1.0
 */
import type { UserSettingsTheme } from './userSettingsTheme'
import type { UserSettingsNotifications } from './userSettingsNotifications'

export interface UserSettings {
  currency?: string
  timezone?: string
  hideZeroBalanceAccounts?: boolean
  theme?: UserSettingsTheme
  /**
   * @minimum 0
   * @maximum 180
   */
  neutralizationLookaroundDays?: number
  analysisSankeyEnabled?: boolean
  notifications?: UserSettingsNotifications
}
