/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedAnalysisRouteImport } from './routes/_authed/analysis'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as AuthedSplatRouteImport } from './routes/_authed/$'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalysisRoute = AuthedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSplatRoute = AuthedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof AuthedSplatRoute
  '/accounts': typeof AuthedAccountsRoute
  '/analysis': typeof AuthedAnalysisRoute
  '/home': typeof AuthedHomeRoute
  '/settings': typeof AuthedSettingsRoute
  '/transactions': typeof AuthedTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof AuthedSplatRoute
  '/accounts': typeof AuthedAccountsRoute
  '/analysis': typeof AuthedAnalysisRoute
  '/home': typeof AuthedHomeRoute
  '/settings': typeof AuthedSettingsRoute
  '/transactions': typeof AuthedTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/$': typeof AuthedSplatRoute
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/analysis': typeof AuthedAnalysisRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/accounts'
    | '/analysis'
    | '/home'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/accounts'
    | '/analysis'
    | '/home'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/$'
    | '/_authed/accounts'
    | '/_authed/analysis'
    | '/_authed/home'
    | '/_authed/settings'
    | '/_authed/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analysis': {
      id: '/_authed/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthedAnalysisRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$': {
      id: '/_authed/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthedSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSplatRoute: typeof AuthedSplatRoute
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedAnalysisRoute: typeof AuthedAnalysisRoute
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSplatRoute: AuthedSplatRoute,
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedAnalysisRoute: AuthedAnalysisRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
